# To preview paste this yaml into editor:
# https://editor.swagger.io/

swagger: "2.0"
info:
  description: "Definicja API dla lodki wolontariatu"
  version: "2.0.0"
  title: "API lodka wolontariatu"
  contact:
    email: "mateusz.maciej.kojro@cern.h"
host: "none"
basePath: "/v1"
schemes:
  - "https"
paths:
  /offers:
    get:
      summary: "List all offers"
      description: ""
      operationId: "listOffers"
      produces:
        - "application/json"
      responses:
        "200":
          description: "success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/OfferInfoOut"
        "404":
          description: "offer not found"
        "500":
          description: "internal server error"

  /offers/add:
    post:
      summary: "Add a new offer"
      description: ""
      operationId: "addOffer"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Offer object to add"
          required: true
          schema:
            $ref: "#/definitions/OfferInfoIn"
      responses:
        "200":
          description: "success"
          schema:
            $ref: "#/definitions/OfferInfoOut"
        "404":
          description: "offer not found"
        "405":
          description: "Invalid input"
        "500":
          description: "internal server error"

  /offers/delete/{id}:
    delete:
      summary: "Delete offer"
      description: ""
      operationId: "deleteOffer"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: Numeric ID of the offer to delete
      responses:
        "200":
          description: "success"
          schema:
            $ref: "#/definitions/OfferInfoOut"
        "404":
          description: "offer not found"
        "405":
          description: "Invalid input"
        "500":
          description: "internal server error"

  /offers/{id}:
    get:
      summary: "Get the offer details"
      description: ""
      operationId: "getOffer"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: Numeric ID of the offer to get
      responses:
        "200":
          description: "success"
          schema:
            $ref: "#/definitions/OfferInfoOut"
        "404":
          description: "offer not found"
        "405":
          description: "Invalid input"
        "500":
          description: "internal server error"

  /volunteers:
    get:
      summary: "List all volunteers"
      description: ""
      operationId: "listVolunteers"
      produces:
        - "application/json"
      responses:
        "200":
          description: "All volunteers"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/VolunteerInfoOut"
        "405":
          description: "Invalid input"
        "500":
          description: "internal server error"

  /volunteers/add:
    post:
      summary: "Add a new volunteer"
      description: ""
      operationId: "addVolunteer"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "volunteer object to add"
          required: true
          schema:
            $ref: "#/definitions/VolunteerInfoIn"
      responses:
        "200":
          description: "Created Volunteer"
          schema:
            $ref: "#/definitions/VolunteerInfoOut"
        "405":
          description: "Invalid input"
        "500":
          description: "internal server error"

  /volunteers/delete/{id}:
    delete:
      summary: "Delete volunteer"
      description: ""
      operationId: "deleteVolunteers"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: Numeric ID of the volunteer to delete
      responses:
        "200":
          description: "Deleted volunteer"
          schema:
            $ref: "#/definitions/VolunteerInfoOut"
        "404":
          description: "volunteer not found"
        "405":
          description: "Invalid input"
        "500":
          description: "internal server error"

  /volunteers/{id}:
    get:
      summary: "Get the volunteer details"
      description: ""
      operationId: "getVolunteer"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: Numeric ID of the volunteer to get
      responses:
        "200":
          description: Volunteer information
          schema:
            $ref: "#/definitions/VolunteerInfoOut"
        "404":
          description: "volunteer not found"
        "405":
          description: "Invalid input"
        "500":
          description: "internal server error"

  /volunteers/skills/{id}:
    get:
      summary: "Get the skills of a volunteer"
      description: ""
      operationId: "getVolunteerSkills"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: Numeric ID of the volunteer to get
      responses:
        "200":
          description: ok
          schema:
            $ref: "#/definitions/volunteerSkillsOut"
        "404":
          description: "volunteer not found"
        "405":
          description: "Invalid input"
        "500":
          description: "internal server error"

  /organizations:
    get:
      summary: "List all organizations"
      description: ""
      operationId: "listOrganizations"
      produces:
        - "application/json"
      responses:
        "200":
          description: "All organizations"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Organization"
        "500":
          description: "internal server error"

  /organizations/add:
    post:
      summary: "Add a new organization"
      description: ""
      operationId: "addOrganization"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Organization to add"
          required: true
          schema:
            $ref: "#/definitions/Organization"
      responses:
        "200":
          description: Created organization
          schema:
            $ref: "#/definitions/Organization"
        "405":
          description: "Invalid input"
        "500":
          description: "internal server error"

  /organizations/delete/{id}:
    delete:
      summary: "Delete organization"
      description: ""
      operationId: "deleteOrganization"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: Numeric ID of the organization to delete
      responses:
        "200":
          description: Removed organization
          schema:
            $ref: "#/definitions/Organization"
        "404":
          description: "organization not found"
        "405":
          description: "Invalid input"
        "500":
          description: "internal server error"

  /organization/{id}:
    get:
      summary: "Get the organization details"
      description: ""
      operationId: "getOrganization"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: Numeric ID of the organization to get
      responses:
        "200":
          description: Organization information
          schema:
            $ref: "#/definitions/Organization"
        "404":
          description: "organization not found"
        "405":
          description: "Invalid input"
        "500":
          description: "internal server error"

definitions:
  VolunteerInfoIn:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      birthDate:
        type: "string"
        format: "date"
      adres:
        type: "string"
        format: "adres"
      accountVerified:
        type: "boolean"
      parentApproved:
        type: "boolean"

  VolunteerInfoOut:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      surname:
        type: "string"
      email:
        type: "string"
        format: "email_format"
      registrationDate:
        type: "string"
        format: "data_format"
      phoneNumber:
        type: "string"
        format: "numbers_only"
      photoUrl:
        type: "string"
        format: "url"
      status:
        type: "string"
        enum: ["ACTIVE", "BLOCKED", "DELETED", "DECEASED", "DEPRESSED"]
      birthDate:
        type: "string"
        format: "date"
      adres:
        type: "string"
        format: "adresu"
      accountVerified:
        type: "boolean"
      parentApproved:
        type: "boolean"

  OfferInfoOut:
    type: "object"
    properties:
      offerId:
        type: "integer"
        format: "int64"
      organizationId:
        type: "integer"
        format: "int64"
      organizationName:
        type: "string"
      region:
        type: "string"
      mainLocation:
        type: "string"
      volunteeringType:
        type: "string"
        enum: ["akcyjny"]
      availablePositions:
        type: "integer"
        format: "int64"
      takenPositions:
        type: "integer"
        format: "int64"
      startDate:
        type: "string"
        format: "date"
      endDate:
        type: "string"
        format: "date"
      description:
        type: "string"
      visibility:
        type: "string"
        enum: ["EVERYONE"]
      offerStatus:
        type: "string"
        enum: ["ACTIVE"]
      coordinatorId:
        type: "integer"
        format: "int64"
      minAge:
        type: "integer"
        format: "int64"
      neededSkills:
        type: "string"
        format: "comma separated skills"
      coordinator_name:
        type: "string"
      coordinatorSurname:
        type: "string"
      coordinatorPhone:
        type: "string"
        format: "number only phone number"

  OfferInfoIn:
    type: "object"
    properties:
      offerId:
        type: "integer"
        format: "int64"
      organizationId:
        type: "integer"
        format: "int64"
      organization_name:
        type: "string"
      region:
        type: "string"
      mainLocation:
        type: "string"
      volunteeringType:
        type: "string"
        enum: ["DŁUGOTERMINOWY", "AKCYJNY"]
      availablePositions:
        type: "integer"
        format: "int64"
      takenPositions:
        type: "integer"
        format: "int64"
      startDate:
        type: "string"
        format: "date"
      endDate:
        type: "string"
        format: "date"
      description:
        type: "string"
      neededSkills:
        type: "string"
        format: "comma separated skills"
      visibility:
        type: "string"
        enum: ["EVERYONE"]
      offerStatus:
        type: "string"
        enum: ["ACTIVE"]
      coordinatorId:
        type: "integer"
        format: "int64"

  Organization:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      organizationName:
        type: "string"
      address:
        type: "string"
      type:
        type: "string"
        enum: ["FUNDACJA"]
      status:
        type: "string"
        enum: ["AKTYWNA"]
      description:
        type: "string"
      workArea:
        type: "string"
      volunteeringType:
        type: "string"
        enum: ["DŁUGOTERMINOWY", "AKCYJNY"]
      registrationDate:
        type: "string"
        format: "date"
      region:
        type: "string"
      logoUrl:
        type: "string"
        format: "http url"

  OrganizationAdminsOut:
    type: "object"
    properties:
      organizationId:
        type: "integer"
        format: "int64"
      userId:
        type: "integer"
        format: "int64"

  volunteerSkillsOut:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      skill:
        type: "string"
        format: "comma separated skills"
